app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# -*- coding: UTF-8 -*-
import os
import datetime
from flask import render_template, abort, flash, redirect, url_for, request
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from . import home
from ..admin.forms import AnchorForm, PenaltyForm
from ..models import Anchor, Penalty
from .. import db


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)

    return render_template('home/admin_dashboard.html', title="Dashboard")

@home.route('/dashboard/add_anchor', methods=['GET', 'POST'])
@login_required
def add_anchor():
    """
    Add an anchor 
    """

    add_anchor = True

    form = AnchorForm()
    del form.photo
    del form.entry_time

    if form.validate_on_submit():
        anchor = Anchor(
            name=form.name.data,
            entry_time=datetime.datetime.now().strftime("%Y-%m-%d"),
            address=form.address.data,
            mobile_number=form.mobile_number.data,
            id_number=form.id_number.data,
            basic_salary_or_not=form.basic_salary_or_not.data,
            basic_salary=form.basic_salary.data,
            live_time=form.live_time.data,
            live_session=form.live_session.data,
            percentage=form.percentage.data,
            ace_anchor_or_not=form.ace_anchor_or_not.data,
            agent=form.agent.data
        )
        try:
            db.session.add(anchor)
            db.session.commit()

            directory = '/home/qi/projects/maomao_files/' + form.name.data
            if not os.path.exists(directory):
                os.mkdir(directory)

            flash('You have successfully added a new anchor.')
        except:
            flash('Error: anchor name already exists.')

        return redirect(url_for('home.dashboard'))

    return render_template('admin/anchors/anchor.html', action="Add", form=form,
                           add_anchor=add_anchor, title="Add Anchor")


@home.route('/dashboard/penalty_form', methods=['GET', 'POST'])
@login_required
def add_penalty():
    """
    Add a penalty input
    """
    form = PenaltyForm()

    if form.validate_on_submit():
        penalty = Penalty(
            anchor_momo=form.momo_number.data,
            date=datetime.date.today().strftime("%Y-%m-%d"),
            amount=form.amount.data
        )
        try:
            db.session.add(penalty)
            db.session.commit()

            flash(u'此罚款记录已成功录入')
        except:
            flash(u'错误:此陌陌号不存在, 请验证输入的陌陌号重试')

        return redirect(url_for('home.dashboard'))

    return render_template('home/add_penalty.html', form=form,
                            title="Add Penalty")

app/templates/home/add_penalty.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %} ?? {% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
				<br/>
        {{ utils.flashed_messages() }}
        <br/>
        <div class="center">
						{% from "_formhelpers.html" import render_field %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/admin_dashboard.html
{% extends "base.html" %}
{% block title %}Admin Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <a href="{{ url_for('admin.system_info') }}" class="btn btn-default btn-lg">System</a>
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>For administrators only!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/dashboard.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <a href="{{ url_for('home.add_anchor') }}" class="btn btn-default btn-lg">Add New Anchor</a>
                    <a href="{{ url_for('home.add_penalty') }}" class="btn btn-default btn-lg">??????</a>
                    <!--<h1>The Dashboard</h1>
                    <h3>We made it here!</h3>
                    <hr class="intro-divider">
                    </ul>-->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
<!-- app/templates/home/index.html -->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Qi's Small Project</h1>
                    <h3>The best project in the world!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}